// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ZZOX3l3RqLzeids8OQBydQR905dCi5k',
    appId: '1:93463333113:web:78bab338177effd2247a28',
    messagingSenderId: '93463333113',
    projectId: 'tree-census-8c0f0',
    authDomain: 'tree-census-8c0f0.firebaseapp.com',
    databaseURL: 'https://tree-census-8c0f0-default-rtdb.firebaseio.com',
    storageBucket: 'tree-census-8c0f0.firebasestorage.app',
    measurementId: 'G-3PNYY7K37J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Z-G9JalNfeoNWnBnZpZ1TPQVwgbEL4s',
    appId: '1:93463333113:android:0aa990f9e717e382247a28',
    messagingSenderId: '93463333113',
    projectId: 'tree-census-8c0f0',
    databaseURL: 'https://tree-census-8c0f0-default-rtdb.firebaseio.com',
    storageBucket: 'tree-census-8c0f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbLr8c8FKIZGEcX0hzNnNT8SdSfaVAKFo',
    appId: '1:93463333113:ios:13e4b83d5abe0243247a28',
    messagingSenderId: '93463333113',
    projectId: 'tree-census-8c0f0',
    databaseURL: 'https://tree-census-8c0f0-default-rtdb.firebaseio.com',
    storageBucket: 'tree-census-8c0f0.firebasestorage.app',
    iosBundleId: 'com.example.treeCensus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbLr8c8FKIZGEcX0hzNnNT8SdSfaVAKFo',
    appId: '1:93463333113:ios:13e4b83d5abe0243247a28',
    messagingSenderId: '93463333113',
    projectId: 'tree-census-8c0f0',
    databaseURL: 'https://tree-census-8c0f0-default-rtdb.firebaseio.com',
    storageBucket: 'tree-census-8c0f0.firebasestorage.app',
    iosBundleId: 'com.example.treeCensus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ZZOX3l3RqLzeids8OQBydQR905dCi5k',
    appId: '1:93463333113:web:abb286e1166c4b4d247a28',
    messagingSenderId: '93463333113',
    projectId: 'tree-census-8c0f0',
    authDomain: 'tree-census-8c0f0.firebaseapp.com',
    databaseURL: 'https://tree-census-8c0f0-default-rtdb.firebaseio.com',
    storageBucket: 'tree-census-8c0f0.firebasestorage.app',
    measurementId: 'G-X7HS5BCSE9',
  );
}
